
FROM  snasello/liferay-6.2


#docker run --name lep-mysql -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_USER=lportal #-e MYSQL_PASSWORD=lportal -e MYSQL_DATABASE=lportal -d mysql:5.6

#docker run --rm -it -p 8080:8080 --link lep-mysql:db_lep -e DB_TYPE=MYSQL snasello/#liferay-6.2:6.2-ce-ga6


# Start MySQL image
# docker run --name osbi-mysql -e MYSQL_ROOT_PASSWORD=mysecretpassword -e MYSQL_USER=lportal -e MYSQL_PASSWORD=lportal -e MYSQL_DATABASE=lportal -d mysql:5.6
#
# Start Liferay image with a link to the MySQL database
# docker run --name osbi-liferay --rm -it -p 8080:8080 --link osbi-mysql:db_lep -e DB_TYPE=MYSQL osbi-liferay

#COPY 
#