# Docker Compose file that brings up pentaho and demo analytics databases
# To run:  docker-compose -f nibrs-compose.yaml up -d
version: '3'

networks:
  nibrs_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.18.0.0/16

services:

  nibrs-db:
    container_name: nibrs-db
    image: searchncjis/nibrs-db
    networks:
      nibrs_nw:

  nibrs-httpd-proxy:
    container_name: nibrs-httpd-proxy
    image: searchncjis/nibrs-httpd-proxy
    networks:
      nibrs_nw:
    ports: 
      - "443:443"
      - "80:80"
    # we need this volume since this SSL cert and key must be on the docker host file system
    volumes:
      - "/opt/certs/:/opt/certs/" 
    
  nibrs-web:
    container_name: nibrs-web
    image: searchncjis/nibrs-web
    networks:
      nibrs_nw:
   
  nibrs-saiku:
    container_name: nibrs-saiku
    image: searchncjis/nibrs-saiku
    networks:
      nibrs_nw:
      
