#This is an image for Gfipm's SP, it just copies in a new set of SAML metadata 
FROM ojbc/portal
MAINTAINER Open Justice Broker Consortium "http://www.ojbc.org"
#
COPY files/demostate-ctf-osbi.xml /opt/shibboleth-sp/etc/shibboleth/demostate-ctf.xml
COPY files/shibboleth2.xml /opt/shibboleth-sp/etc/shibboleth/